### ISSUE TITLE
Microsoft Edge Legacy Installer

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [Legacy-Edge/Legacy-Edge-Launcher#10]
After three years of failed attempts I finally managed to compile the last version of Edge Legacy into an appx file, but unfortunately upon clicking on install, it simply shows the error shown in the image. The appx is attached as well as the certificate for it if you'd like to attempt this for yourselves. Any solutions would be much appreciated
![microsoft-edge-legacy-installer-v0-w6fts8ge8r3d1](https://github.com/Legacy-Edge/Legacy-Edge-Launcher/assets/82360021/b7c070a0-05b3-4b61-a19f-1e959988618d)
[Edge.zip](https://github.com/user-attachments/files/15514570/Edge.zip)

**Comment by ShortDevelopment** [comment]
Legacy Edge uses some capabilities that are not allowed for normal appx packages. 
There seems to be a registry key to allow the installation of such packages.

> [!CAUTION]
> Please keep in mind that this browser does not receive any security updates any more!!

**Comment by ThunderboltCommunicationsCorp** [comment]
Do you happen to know what that registry key is and where it's located? Also does the registry key already exist, does it need to be added and does it need to be modified? If yes then what?

**Comment by ShortDevelopment** [comment]
https://gist.github.com/ADeltaX/caa47043b2d39d3c30680164dc31a1ab
